#!/usr/bin/env -S deno run -A
/**
 * Codegen: reads src/dashboard/templates/* and generates
 * src/dashboard/templates.generated.ts with string exports.
 *
 * Run: deno run -A scripts/gen_templates.ts
 * Or:  ./scripts/gen_templates.ts
 */

import { join } from "@std/path";

const TEMPLATE_DIR = join(Deno.cwd(), "src", "dashboard", "templates");
const OUTPUT = join(Deno.cwd(), "src", "dashboard", "templates.generated.ts");

const TEMPLATES = [
  "base.html",
  "styles.css",
  "plotly_charts.js",
  "interactions.js",
  "insights.js",
  "live.js",
  "compare.js",
];

const exportName = (filename: string): string =>
  filename
    .replace(/\.[^.]+$/, "")
    .replace(/[^a-zA-Z0-9_]/g, "_");

const lines: string[] = [
  "// AUTO-GENERATED by scripts/gen_templates.ts — do not edit manually.",
  "// Re-generate with: deno run -A scripts/gen_templates.ts",
  "",
];

for (const name of TEMPLATES) {
  const content = await Deno.readTextFile(join(TEMPLATE_DIR, name));
  const varName = exportName(name);
  lines.push(`export const ${varName} = ${JSON.stringify(content)};`);
  lines.push("");
}

await Deno.writeTextFile(OUTPUT, lines.join("\n"));
console.log(`Generated ${OUTPUT}`);
